In [2]:
import torch

In [4]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
y.grad_fn

In [7]:
z = y * y * 3
out = z.mean()

In [8]:
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [9]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [10]:
out.backward()

In [21]:
xx = out.detach()

`autograd`는 자동으로 경사하강법을 사용할수 있도록 도와주는 기능이다.
`Tensor` 클래스의 `require_grad`를 `True`로 할시 사용할수 있다.

`require_grad`를 사용하게 되면 그 텐서의 모든 연산을 자동적으로 기록한다.
만약 최종적으로 연산된 결과물이 스칼라일 경우, `.backward()` 메소드를 이용해서 지금까지의 연산으로 미분하게 된다.

연산 기록을 남기고 싶지 않다면 `.detach()` 메소드를 사용하자.
그렇다면 `require_grad=False` 인 텐서를 얻을수 있다.

새로운 객체를 얻고 싶지 않다면 `.require_grad_(False)`를 사용하자. 그렇다면 기존의 텐서가 연산 기록을 중단할것이다.