# 기초 텐서

### 텐서 선언

In [12]:
import torch

torch.empty(3)
'''
result : tensor([6.7706e+22, 1.0674e-08, 2.1650e+23])
'''
torch.empty(2,2,3)
'''
result : 
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
'''
torch.rand(2, 2)
'''
result : 
tensor([[0.7781, 0.6035],
        [0.3431, 0.8024]])
항상 바뀜!
'''
torch.tensor([2.5 ,0.1])
'''
result : tensor([2.5000, 0.1000])
'''

tensor([2.5000, 0.1000])

In [9]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

### 텐서 타입 지정

In [10]:
x = torch.ones(2, 2)
print(x.dtype)
x = torch.ones(2, 2, dtype=torch.int)
print(x.dtype)
x = torch.ones(2, 2, dtype=torch.double)
print(x.dtype)

torch.float32
torch.int32
torch.float64


### 텐서 크기

In [11]:
x = torch.ones(2,2)
x.size()

torch.Size([2, 2])

### 텐서 연산

In [13]:
x = torch.tensor([2,2])
y = torch.tensor([1,5])

x + y
torch.add(x, y)
y.add_(x) # y += x

x - y
torch.mul(x, y)
y.div_(x)

tensor([3, 7])

### 텐서 선택 (인덱싱)

In [15]:
x = torch.rand(5, 3)
print(x)
print(x[1, :])
print(x[1, 1])
print(x[1, 1].item()) # 실제 값을 리턴함 (오직 하나의 요소만 있을때 가능)

tensor([[0.5118, 0.5521, 0.0285],
        [0.9465, 0.0076, 0.0234],
        [0.9360, 0.4874, 0.8782],
        [0.6202, 0.7136, 0.0648],
        [0.4219, 0.5991, 0.1202]])
tensor([0.9465, 0.0076, 0.0234])
tensor(0.0076)


### 텐서 리사이징

In [18]:
x = torch.rand(4, 4)
print(x.size())
y = x.view(16)
print(y.size())
y = x.view(-1, 8) # -1은 자동으로 크기 선택 (2, 8) 
print(y.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


### 텐서 -> Numpy

In [20]:
import numpy as np

x = torch.ones(5)
print(x)
y = x.numpy()
print(type(y))

# numpy 배열과 torch.tensor는 메모리를 공유함

x.add_(1)

print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy -> 텐서

In [23]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a) # dtype 조정 가능
print(b)

# a와 b는 같은 메모리를 공유함

a += 1

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### GPU 내부에 텐서 만들기

In [ ]:
if torch.cuda.is_available():
  # CUDA가 설치되어 있을 경우
  device = torch.device("cuda")

  # GPU 내부에 텐서 생성
  x = torch.ones(5, device=device)
  
  # CPU에 있던 텐서를 GPU로
  y = torch.ones(5)
  y = y.to(device)

  # 더 빠르게 연산이 가능
  z = x + y

  # 주의!
  # z.numpy() 하면 에러가 호출됨!
  # 넘파이는 오직 CPU만 핸들 가능함

  # CPU로 다시 데이터 옮기기
  z = z.to("cpu")

### 기울기 계산 필수

In [ ]:
# 후일 최적화 단계에서 기울기를 계산해야된다는 것을 Pytorch에게 알려줌
# 기본값은 False
x = torch.ones(5, requires_grad=True)
print(x)