In [20]:
import torch

In [21]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [22]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [23]:
y.grad_fn

In [24]:
z = y * y * 3
out = z.mean()

In [25]:
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [26]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [27]:
out.backward()

In [28]:
xx = out.detach()

`autograd`는 자동으로 경사하강법을 사용할수 있도록 도와주는 기능이다.
`Tensor` 클래스의 `require_grad`를 `True`로 할시 사용할수 있다.

`require_grad`를 사용하게 되면 그 텐서의 모든 연산을 자동적으로 기록한다.
만약 최종적으로 연산된 결과물이 스칼라일 경우, `.backward()` 메소드를 이용해서 지금까지의 연산으로 미분하게 된다.

연산 기록을 남기고 싶지 않다면 `.detach()` 메소드를 사용하자.
그렇다면 `require_grad=False` 인 텐서를 얻을수 있다.

새로운 객체를 얻고 싶지 않다면 `.require_grad_(False)`를 사용하자. 그렇다면 기존의 텐서가 연산 기록을 중단할것이다.

어느 한 부분만 기록을 중단하고 싶다면 `with torch.no_grad()` 를 사용하자

`.backward()` 는 기록된 연산들을 미분하고 그 기울기를 반환한다.

밑의 식을 $ \sigma $ 라 했을때 $ \sigma = {1 \over 4} \Sigma (x + 3) ^ x$ 라고 할수 있다. 

backward()` 는 기록된 연산들을 미분하고 그 기울기를 반환한다.

밑의 식을 $ \sigma $ 라 했을때 $ \sigma = {1 \over 4} \Sigma (x + 3) ^ x$ 라고 할수 있다. 

이 식의 미분식은 $ {1 \over 4} (2x + 2) $ 그러므로 $ x = 1 $ 일때 기울기는 1.25이다

In [29]:
t = torch.ones(2, 2, requires_grad=True)
t

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [30]:
t1 = (t + 3) * t
t1

tensor([[4., 4.],
        [4., 4.]], grad_fn=<MulBackward0>)

In [31]:
tm = torch.mean(t1)
tm

tensor(4., grad_fn=<MeanBackward0>)

In [32]:
tm.backward()

In [33]:
(t.grad, t)

(tensor([[1.2500, 1.2500],
         [1.2500, 1.2500]]),
 tensor([[1., 1.],
         [1., 1.]], requires_grad=True))