In [1]:
import torch

In [2]:
torch.empty(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [3]:
torch.rand(5,5)

tensor([[0.6484, 0.6598, 0.9179, 0.7257, 0.7992],
        [0.0073, 0.7806, 0.3387, 0.5551, 0.4984],
        [0.9814, 0.8011, 0.7590, 0.4046, 0.0732],
        [0.8008, 0.2085, 0.1773, 0.7846, 0.6710],
        [0.4444, 0.1428, 0.8956, 0.8848, 0.8016]])

In [4]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [13]:
x = x.new_ones(5, 3, dtype=torch.double)

In [14]:
torch.randn_like(x, dtype=torch.float)

tensor([[ 0.2100,  0.8799,  0.6979],
        [ 1.0520,  0.1711, -0.0317],
        [ 0.7006, -0.2510,  1.4075],
        [-0.4562, -1.2436, -0.8229],
        [ 1.0810, -0.7797,  0.1823]])

In [15]:
x.size()

torch.Size([5, 3])

In [18]:
y = torch.rand(x.size())
x + y; torch.add(x, y)

tensor([[1.3782, 1.5598, 1.6113],
        [1.3320, 1.4587, 1.5850],
        [1.6348, 1.9248, 1.3280],
        [1.0502, 1.5261, 1.8413],
        [1.7092, 1.2728, 1.8173]], dtype=torch.float64)

In [22]:
result = torch.empty(x.size())
torch.add(x, y, out=result)
result

tensor([[1.3782, 1.5598, 1.6113],
        [1.3320, 1.4587, 1.5850],
        [1.6348, 1.9248, 1.3280],
        [1.0502, 1.5261, 1.8413],
        [1.7092, 1.2728, 1.8173]])

In [23]:
y.add_(x) v # +=

tensor([[1.3782, 1.5598, 1.6113],
        [1.3320, 1.4587, 1.5850],
        [1.6348, 1.9248, 1.3280],
        [1.0502, 1.5261, 1.8413],
        [1.7092, 1.2728, 1.8173]])

In [26]:
x[:, 1]

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [29]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # -1은 자동으로 설정
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [30]:
x = torch.randn(1)
print(x, x.item())

tensor([0.3115]) 0.3115420639514923


In [32]:
a = torch.ones(5, 5)
print(type(a))
b = a.numpy()
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [33]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [34]:
# 이 코드는 CUDA가 설치되어 있어야 합니다.

if torch.cuda.is_available():
    device = torch.device("cuda")           # CUDA 장치 객체 선언
    y = torch.ones_like(x, device=device)   # GPU 내부에 직접적으로 tensor를 생성
    x = x.to(device)                        # 객체를 GPU 내부로 전송
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))        # CPU 로도 전송 가능

tensor([1.3115], device='cuda:0')
tensor([1.3115], dtype=torch.float64)


In [35]:
gpu = torch.ones(5, 5, device=device)
cpu = torch.ones(5, 5)

gpu + cpu # 생성 위치가 다른 객체는 서로 연산이 불가능

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!